<a href="https://colab.research.google.com/github/zecenbajra55/1100python/blob/main/machine_learning_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# encoding categorical variables

In [ ]:
import pandas as pd
df = pd.DataFrame({'education':['bachelors','phd','phd','masters','masters','bachelors']})

In [ ]:
df

education
0  bachelors
1        phd
2        phd
3    masters
4    masters
5  bachelors

# one hot encoding

In [ ]:
pd.get_dummies(columns = ['education'],data =df)

education_bachelors  education_masters  education_phd
0                    1                  0              0
1                    0                  0              1
2                    0                  0              1
3                    0                  1              0
4                    0                  1              0
5                    1                  0              0

In [ ]:
# remove multi colinarity by dropping first column
pd.get_dummies(columns=['education'],data=df,drop_first = True)

education_masters  education_phd
0                  0              0
1                  0              1
2                  0              1
3                  1              0
4                  1              0
5                  0              0

# one hot encoding using sklearn

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
encoder = OneHotEncoder(sparse_output = False) # sparse_output = False returns numpy array
encoder.fit(df[['education']]) # .fit() method needs data in 2D
encoded=encoder.transform(df[['education']])
encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
encoder.categories_

[array(['bachelors', 'masters', 'phd'], dtype=object)]

In [ ]:
pd.DataFrame(encoded, columns = encoder.categories_)

bachelors masters  phd
0       1.0     0.0  0.0
1       0.0     0.0  1.0
2       0.0     0.0  1.0
3       0.0     1.0  0.0
4       0.0     1.0  0.0
5       1.0     0.0  0.0

In [ ]:
encoder = OneHotEncoder(sparse_output = False,drop ='first') # sparse_output = False returns numpy array
encoder.fit(df[['education']]) # .fit() method needs data in 2D
encoded=encoder.transform(df[['education']])
encoded

array([[0., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.]])

# label encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoder.fit(df['education'])  #  .fit() expects 1D
encoder.transform(df['education'])

array([0, 2, 2, 1, 1, 0])

In [ ]:
encoder.classes_

array(['bachelors', 'masters', 'phd'], dtype=object)

In [ ]:
encoder = LabelEncoder()
encoder.fit_transform(df['education'])

array([0, 2, 2, 1, 1, 0])