<a href="https://colab.research.google.com/github/zecenbajra55/1100python/blob/main/natural_language_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# text preprocessing

## tokenization : converting sentence into words

In [ ]:
sent = "tokenization is the task of splitting a text into meaningful segments called tokens"

In [ ]:
import nltk # natural language tool kit
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
words=nltk.word_tokenize(sent)

In [ ]:
words

['tokenization',
 'is',
 'the',
 'task',
 'of',
 'splitting',
 'a',
 'text',
 'into',
 'meaningful',
 'segments',
 'called',
 'tokens']

In [ ]:
paragraph = 'i am a student. i like history as a subject.'

In [ ]:
nltk.sent_tokenize(paragraph)

['i am a student.', 'i like history as a subject.']

words like is, the , of ,a is not much important because it doesnt add much meaning to the sentence we can remove them using stopwords.

## stopwords

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
nltk.corpus.stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
nltk.corpus.stopwords.words('nepali')

['छ',
 'र',
 'पनि',
 'छन्',
 'लागि',
 'भएको',
 'गरेको',
 'भने',
 'गर्न',
 'गर्ने',
 'हो',
 'तथा',
 'यो',
 'रहेको',
 'उनले',
 'थियो',
 'हुने',
 'गरेका',
 'थिए',
 'गर्दै',
 'तर',
 'नै',
 'को',
 'मा',
 'हुन्',
 'भन्ने',
 'हुन',
 'गरी',
 'त',
 'हुन्छ',
 'अब',
 'के',
 'रहेका',
 'गरेर',
 'छैन',
 'दिए',
 'भए',
 'यस',
 'ले',
 'गर्नु',
 'औं',
 'सो',
 'त्यो',
 'कि',
 'जुन',
 'यी',
 'का',
 'गरि',
 'ती',
 'न',
 'छु',
 'छौं',
 'लाई',
 'नि',
 'उप',
 'अक्सर',
 'आदि',
 'कसरी',
 'क्रमशः',
 'चाले',
 'अगाडी',
 'अझै',
 'अनुसार',
 'अन्तर्गत',
 'अन्य',
 'अन्यत्र',
 'अन्यथा',
 'अरु',
 'अरुलाई',
 'अर्को',
 'अर्थात',
 'अर्थात्',
 'अलग',
 'आए',
 'आजको',
 'ओठ',
 'आत्म',
 'आफू',
 'आफूलाई',
 'आफ्नै',
 'आफ्नो',
 'आयो',
 'उदाहरण',
 'उनको',
 'उहालाई',
 'एउटै',
 'एक',
 'एकदम',
 'कतै',
 'कम से कम',
 'कसै',
 'कसैले',
 'कहाँबाट',
 'कहिलेकाहीं',
 'का',
 'किन',
 'किनभने',
 'कुनै',
 'कुरा',
 'कृपया',
 'केही',
 'कोही',
 'गए',
 'गरौं',
 'गर्छ',
 'गर्छु',
 'गर्नुपर्छ',
 'गयौ',
 'गैर',
 'चार',
 'चाहनुहुन्छ',
 'चाहन्छु',
 'चाहिए

In [ ]:
nltk.corpus.stopwords.words('russian')

['и',
 'в',
 'во',
 'не',
 'что',
 'он',
 'на',
 'я',
 'с',
 'со',
 'как',
 'а',
 'то',
 'все',
 'она',
 'так',
 'его',
 'но',
 'да',
 'ты',
 'к',
 'у',
 'же',
 'вы',
 'за',
 'бы',
 'по',
 'только',
 'ее',
 'мне',
 'было',
 'вот',
 'от',
 'меня',
 'еще',
 'нет',
 'о',
 'из',
 'ему',
 'теперь',
 'когда',
 'даже',
 'ну',
 'вдруг',
 'ли',
 'если',
 'уже',
 'или',
 'ни',
 'быть',
 'был',
 'него',
 'до',
 'вас',
 'нибудь',
 'опять',
 'уж',
 'вам',
 'ведь',
 'там',
 'потом',
 'себя',
 'ничего',
 'ей',
 'может',
 'они',
 'тут',
 'где',
 'есть',
 'надо',
 'ней',
 'для',
 'мы',
 'тебя',
 'их',
 'чем',
 'была',
 'сам',
 'чтоб',
 'без',
 'будто',
 'чего',
 'раз',
 'тоже',
 'себе',
 'под',
 'будет',
 'ж',
 'тогда',
 'кто',
 'этот',
 'того',
 'потому',
 'этого',
 'какой',
 'совсем',
 'ним',
 'здесь',
 'этом',
 'один',
 'почти',
 'мой',
 'тем',
 'чтобы',
 'нее',
 'сейчас',
 'были',
 'куда',
 'зачем',
 'всех',
 'никогда',
 'можно',
 'при',
 'наконец',
 'два',
 'об',
 'другой',
 'хоть',
 'после',
 'на

In [ ]:
sent = "tokenization is the task of splitting a text into meaningful segments, called tokens."
words=nltk.word_tokenize(sent)
print(words)

['tokenization', 'is', 'the', 'task', 'of', 'splitting', 'a', 'text', 'into', 'meaningful', 'segments', ',', 'called', 'tokens', '.']


In [ ]:
[word for word in words if word.lower() not in set(nltk.corpus.stopwords.words('english'))]

['tokenization',
 'task',
 'splitting',
 'text',
 'meaningful',
 'segments',
 ',',
 'called',
 'tokens',
 '.']

# stemming

## it converts words into root words ot base words stem or base words - word may not have any meaning - very fast (doesnt preserve dictionary meaning)

application:
* sentiment analysis
* review analysis
* spam email classifier

In [ ]:
words=['change','changes','changed']

In [ ]:
from nltk.stem.snowball import PorterStemmer
stemmer = PorterStemmer()
[stemmer.stem(item) for item in words]

['chang', 'chang', 'chang']

In [ ]:
words=['do','did','done']
[stemmer.stem(item) for item in words]

['do', 'did', 'done']

# lemmatization:
 it deals with reducing the word to its cannonical dictionary form. the root word is called a lemma and the method is called lemmatization - slow

## application:
* chatbot
* summarization

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
words=['change','changes','changed']
from nltk.stem import WordNetLemmatizer
lemmatizer= WordNetLemmatizer()
[lemmatizer.lemmatize(item) for item in words]

['change', 'change', 'changed']

# text cleaning (HTML)

In [ ]:
title='<h1><b>India</b> and <b>Pakistan</b> shared one point in the last match at <i>Asia Cup</i> 2023.</h1>'

In [ ]:
title

'<h1><b>India</b> and <b>Pakistan</b> shared one point in the last match at <i>Asia Cup</i> 2023.</h1>'

In [ ]:
from bs4 import BeautifulSoup
cleaned = BeautifulSoup(title).text
cleaned

'India and Pakistan shared one point in the last match at Asia Cup 2023.'

using Regex or regular expression

In [ ]:
import re
def remove_html(text):
    p=re.compile(r'<.*?>')
    return p.sub('',text)

In [ ]:
remove_html(text=title)

'India and Pakistan shared one point in the last match at Asia Cup 2023.'

# converting text into vector

corpus vaneko paragraph [d1,d2,d3]

document d1= document,d2=document - sentence or data points

vocabulary= unique words

d1= the food was good - 1

d2= the food was bad - 0

d3= the pizza was good -1

# cat1: bag of words / count vectorzation

adv

* simple

dis

* sparsity
* out of vocabulary problem
* ordering of wotds is not preserved
* semantic meaning lost

# cat2: tf-idf
 it stands for term frequency - inverse data frequency

 tf gives us the frequency of the word in each document in the corpus

 idf is used to calculate the weight of rare words across all document in the coupus. the words that occur rarely in the corpus have a  high idf score

In [ ]:
corpus = ['he is a good boy', 'she is a good girl', 'boy and girl are good']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words='english')

In [ ]:
vectors=vectorizer.fit_transform(corpus)

In [ ]:
vectors

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [ ]:
vectors.toarray()

array([[1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [ ]:
import pandas as pd
pd.DataFrame(vectors.toarray(),columns=vectorizer.get_feature_names_out())

boy  girl  good
0    1     0     1
1    0     1     1
2    1     1     1

count vectorizer ma semantic info capture garna parda n-gram use garna parxa

ngram_range (1,1) rakhda only unigram vanxa
vectorizer = CountVectorizer(stop_words='english',ngram_range=(1,1))

(1,2) lai unigram vanxa

(2,2) lai only bigram



In [ ]:
vectorizer.get_feature_names_out() # vocabulary dinxa

array(['boy', 'girl', 'good'], dtype=object)

In [ ]:
# only unigram
corpus = ['he is a good boy', 'she is a good girl', 'good boy and girl are good']
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
vectorizer = CountVectorizer(stop_words = 'english', ngram_range=(1,1))
vectors = vectorizer.fit_transform(corpus)
pd.DataFrame(vectors.toarray(), columns = vectorizer.get_feature_names_out())


boy  girl  good
0    1     0     1
1    0     1     1
2    1     1     2

In [ ]:
# unigram

corpus = ['he is a good boy', 'she is a good girl', 'good boy and girl are good']
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
vectorizer = CountVectorizer(stop_words = 'english', ngram_range=(1,2))
vectors = vectorizer.fit_transform(corpus)
pd.DataFrame(vectors.toarray(), columns = vectorizer.get_feature_names_out())

boy  boy girl  girl  girl good  good  good boy  good girl
0    1         0     0          0     1         1          0
1    0         0     1          0     1         0          1
2    1         1     1          1     2         1          0

In [ ]:
# only bigram
corpus = ['he is a good boy', 'she is a good girl', 'good boy and girl are good']
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
vectorizer = CountVectorizer(stop_words = 'english', ngram_range=(2,2))
vectors = vectorizer.fit_transform(corpus)
pd.DataFrame(vectors.toarray(), columns = vectorizer.get_feature_names_out())

boy girl  girl good  good boy  good girl
0         0          0         1          0
1         0          0         0          1
2         1          1         1          0

# tf-idf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer(stop_words='english')

In [ ]:
vectors=vectorizer.fit_transform(corpus)

In [ ]:
vectors

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [ ]:
vectors.toarray()

array([[0.78980693, 0.        , 0.61335554],
       [0.        , 0.78980693, 0.61335554],
       [0.47606294, 0.47606294, 0.73941068]])

In [ ]:
import pandas as pd
pd.DataFrame(vectors.toarray(),columns=vectorizer.get_feature_names_out())

boy      girl      good
0  0.789807  0.000000  0.613356
1  0.000000  0.789807  0.613356
2  0.476063  0.476063  0.739411

In [ ]:
a=['The car is driven on the road','The truck is driven on the highway']

In [ ]:
vectors=vectorizer.fit_transform(a)

In [ ]:
vectors.toarray()

array([[0.6316672 , 0.44943642, 0.        , 0.6316672 , 0.        ],
       [0.        , 0.44943642, 0.6316672 , 0.        , 0.6316672 ]])

In [ ]:
pd.DataFrame(vectors.toarray(),columns=vectorizer.get_feature_names_out())

car    driven   highway      road     truck
0  0.631667  0.449436  0.000000  0.631667  0.000000
1  0.000000  0.449436  0.631667  0.000000  0.631667

# regular expression



'^a...s$'
5 letters starting with a and ending with s

case sensitive

In [ ]:
import re
pattern='^a...s$'
test_string='abyss'
result=re.match(pattern,test_string)
if result:
    print('search successful')
else:
    print('search unsuccessful')

search successful


[ ] big bracets it specifies a set of character you wish t0 match'

[abc]
a - 1 match

ac= 2 match

hey jude = no match

ac b a = 4 match

[^] means all expect the characters

[^abc] all except abc

[^ 0-9] all except numbers 0-9

In [ ]:
import re

def extract_emails_from_text(text):
   email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b'
   emails = re.findall(email_pattern, text)
   return emails

# Example usage
text = """
Contact us at the following email addresses for support:
support@example.com
info@example.com
sales@example.com
ram.singh@yoap.to
bajracharya551010@gmail.com
"""

emails = extract_emails_from_text(text)
print(emails)

['support@example.com', 'info@example.com', 'sales@example.com', 'ram.singh@yoap.to', 'bajracharya551010@gmail.com']
